package ru.sportorg.documents;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class DocumentRepository {
    private final JdbcClient jdbc;
    DocumentRepository(JdbcClient jdbc) { this.jdbc = jdbc; }
    boolean organizationExists(UUID org) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :org").param("org", org).query(Long.class).single() > 0; }
    Membership membership(UUID user, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :user AND organization_id = :org AND status = 'ACTIVE'").param("user", user).param("org", org).query((rs, row) -> new Membership(rs.getString("roles"), rs.getString("permissions"))).optional().orElse(null); }
    boolean athleteVisible(UUID org, UUID athlete, UUID user) { return jdbc.sql("SELECT count(*) FROM athlete a WHERE a.organization_id = :org AND a.id = :athlete AND (a.user_id = :user OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :user))").param("org", org).param("athlete", athlete).param("user", user).query(Long.class).single() > 0; }
    boolean athleteExists(UUID org, UUID athlete) { return jdbc.sql("SELECT count(*) FROM athlete WHERE organization_id = :org AND id = :athlete").param("org", org).param("athlete", athlete).query(Long.class).single() > 0; }
    boolean fileVisible(UUID org, UUID fileId, UUID user) { return jdbc.sql("SELECT count(*) FROM document d WHERE d.organization_id = :org AND d.file_id = :file AND (d.athlete_id IS NULL OR d.athlete_id IN (SELECT a.id FROM athlete a WHERE a.user_id = :user OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :user)))").param("org", org).param("file", fileId).param("user", user).query(Long.class).single() > 0; }
    void insertFile(StoredFile file) { jdbc.sql("INSERT INTO stored_file (id, organization_id, original_name, content_type, size_bytes, storage_name, uploaded_by) VALUES (:id, :org, :name, :type, :size, :storage, :user)").param("id", file.id()).param("org", file.organizationId()).param("name", file.originalName()).param("type", file.contentType()).param("size", file.sizeBytes()).param("storage", file.storageName()).param("user", file.uploadedBy()).update(); }
    void deleteFile(UUID org, UUID fileId, UUID user) { jdbc.sql("DELETE FROM stored_file f WHERE f.organization_id = :org AND f.id = :id AND f.uploaded_by = :user AND NOT EXISTS (SELECT 1 FROM document d WHERE d.file_id = f.id)").param("org", org).param("id", fileId).param("user", user).update(); }
    Optional<StoredFile> file(UUID org, UUID id) { return jdbc.sql("SELECT id, organization_id, original_name, content_type, size_bytes, storage_name, uploaded_by, uploaded_at FROM stored_file WHERE organization_id = :org AND id = :id").param("org", org).param("id", id).query((rs, row) -> new StoredFile(rs.getObject("id", UUID.class), rs.getObject("organization_id", UUID.class), rs.getString("original_name"), rs.getString("content_type"), rs.getLong("size_bytes"), rs.getString("storage_name"), rs.getObject("uploaded_by", UUID.class), rs.getTimestamp("uploaded_at").toInstant())).optional(); }
    Document insertDocument(UUID org, UUID athlete, String type, String title, UUID fileId, LocalDate issued, LocalDate valid, UUID user, Instant now) { UUID id = UUID.randomUUID(); jdbc.sql("INSERT INTO document (id, organization_id, athlete_id, type, title, file_id, issued_on, valid_until, created_by, created_at, updated_at) VALUES (:id, :org, :athlete, :type, :title, :file, :issued, :valid, :user, :now, :now)").param("id", id).param("org", org).param("athlete", athlete).param("type", type).param("title", title.trim()).param("file", fileId).param("issued", issued).param("valid", valid).param("user", user).param("now", now).update(); return findDocument(org, id).orElseThrow(); }
    long countDocuments(UUID org, String q, UUID athlete, String type, Boolean expired) { return jdbc.sql("SELECT count(*) FROM document d WHERE d.organization_id = :org AND (:q IS NULL OR position(:q IN lower(d.title)) > 0) AND (:athlete IS NULL OR d.athlete_id = :athlete) AND (:type IS NULL OR d.type = :type) AND (:expired IS NULL OR (:expired = TRUE AND d.valid_until IS NOT NULL AND d.valid_until < CURRENT_DATE) OR (:expired = FALSE AND (d.valid_until IS NULL OR d.valid_until >= CURRENT_DATE)))").param("org", org).param("q", q).param("athlete", athlete).param("type", type).param("expired", expired).query(Long.class).single(); }
    List<Document> documents(UUID org, String q, UUID athlete, String type, Boolean expired, int limit, int offset) { return jdbc.sql("SELECT d.id, d.organization_id, d.athlete_id, d.type, d.title, d.issued_on, d.valid_until, d.created_by, d.created_at, d.updated_at, f.id file_id, f.original_name, f.content_type, f.size_bytes, f.storage_name, f.uploaded_by, f.uploaded_at FROM document d JOIN stored_file f ON f.id = d.file_id WHERE d.organization_id = :org AND (:q IS NULL OR position(:q IN lower(d.title)) > 0) AND (:athlete IS NULL OR d.athlete_id = :athlete) AND (:type IS NULL OR d.type = :type) AND (:expired IS NULL OR (:expired = TRUE AND d.valid_until IS NOT NULL AND d.valid_until < CURRENT_DATE) OR (:expired = FALSE AND (d.valid_until IS NULL OR d.valid_until >= CURRENT_DATE))) ORDER BY d.created_at DESC, d.id DESC LIMIT :limit OFFSET :offset").param("org", org).param("q", q).param("athlete", athlete).param("type", type).param("expired", expired).param("limit", limit).param("offset", offset).query((rs, row) -> mapDocument(rs)).list(); }
    Optional<Document> findDocument(UUID org, UUID id) { return jdbc.sql("SELECT d.id, d.organization_id, d.athlete_id, d.type, d.title, d.issued_on, d.valid_until, d.created_by, d.created_at, d.updated_at, f.id file_id, f.original_name, f.content_type, f.size_bytes, f.storage_name, f.uploaded_by, f.uploaded_at FROM document d JOIN stored_file f ON f.id = d.file_id WHERE d.organization_id = :org AND d.id = :id").param("org", org).param("id", id).query((rs, row) -> mapDocument(rs)).optional(); }
    private Document mapDocument(java.sql.ResultSet rs) throws java.sql.SQLException { StoredFile file = new StoredFile(rs.getObject("file_id", UUID.class), rs.getObject("organization_id", UUID.class), rs.getString("original_name"), rs.getString("content_type"), rs.getLong("size_bytes"), rs.getString("storage_name"), rs.getObject("uploaded_by", UUID.class), rs.getTimestamp("uploaded_at").toInstant()); return new Document(rs.getObject("id", UUID.class), rs.getObject("organization_id", UUID.class), rs.getObject("athlete_id", UUID.class), rs.getString("type"), rs.getString("title"), file, rs.getObject("issued_on", LocalDate.class), rs.getObject("valid_until", LocalDate.class), rs.getObject("created_by", UUID.class), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()); }
    record Membership(String roles, String permissions) { boolean role(String value) { return roles.contains(value); } boolean permission(String value) { return permissions.contains(value); } }
}