package ru.sportorg.events;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import ru.sportorg.jdbc.JdbcTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class EventRepository {
    private final JdbcClient jdbc; private final ObjectMapper mapper;
    EventRepository(JdbcClient jdbc, ObjectMapper mapper) { this.jdbc = jdbc; this.mapper = mapper; }
    boolean organizationExists(UUID org) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :org").param("org", org).query(Long.class).single() > 0; }
    Optional<MembershipAccess> membership(UUID userId, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :userId AND organization_id = :org AND status = 'ACTIVE'").param("userId", userId).param("org", org).query((rs, row) -> new MembershipAccess(readStrings(rs.getString("roles")), readStrings(rs.getString("permissions")))).optional(); }
    boolean sectionExists(UUID org, UUID sectionId) { return jdbc.sql("SELECT count(*) FROM section WHERE organization_id = :org AND id = :id AND status = 'ACTIVE'").param("org", org).param("id", sectionId).query(Long.class).single() > 0; }
    boolean athleteExists(UUID org, UUID athleteId) { return jdbc.sql("SELECT count(*) FROM athlete WHERE organization_id = :org AND id = :id").param("org", org).param("id", athleteId).query(Long.class).single() > 0; }
    boolean eventVisible(UUID eventId, UUID userId) { return jdbc.sql("SELECT count(*) FROM event_participant ep JOIN athlete a ON a.id = ep.athlete_id WHERE ep.event_id = :eventId AND (a.user_id = :userId OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :userId))").param("eventId", eventId).param("userId", userId).query(Long.class).single() > 0; }
    boolean athleteVisible(UUID org, UUID athleteId, UUID userId) { return jdbc.sql("SELECT count(*) FROM athlete a WHERE a.organization_id = :org AND a.id = :athleteId AND (a.user_id = :userId OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :userId))").param("org", org).param("athleteId", athleteId).param("userId", userId).query(Long.class).single() > 0; }
    long count(UUID org, String q, LocalDate from, LocalDate to, String type, String status, UUID scopeUser, String scope) { return jdbc.sql(eventSql("SELECT count(*) FROM event e")).param("org", org).param("q", q).param("fromDate", from).param("toDate", to).param("type", type).param("status", status).param("scopeUser", scopeUser).param("scope", scope).query(Long.class).single(); }
    List<Event> find(UUID org, String q, LocalDate from, LocalDate to, String type, String status, UUID scopeUser, String scope, int limit, int offset) { return jdbc.sql(eventSql("SELECT e.id, e.organization_id, e.title, e.type, e.section_id, e.description, e.starts_at, e.ends_at, e.location, e.cost_per_athlete, e.target_amount, e.collection_due_on, e.response_deadline, e.required_document_types::text required_document_types, e.status, e.created_by, e.created_at, e.updated_at FROM event e") + " ORDER BY e.created_at DESC, e.id DESC LIMIT :limit OFFSET :offset").param("org", org).param("q", q).param("fromDate", from).param("toDate", to).param("type", type).param("status", status).param("scopeUser", scopeUser).param("scope", scope).param("limit", limit).param("offset", offset).query((rs, row) -> map(rs)).list(); }
    Optional<Event> findById(UUID org, UUID id) { return jdbc.sql("SELECT e.id, e.organization_id, e.title, e.type, e.section_id, e.description, e.starts_at, e.ends_at, e.location, e.cost_per_athlete, e.target_amount, e.collection_due_on, e.response_deadline, e.required_document_types::text required_document_types, e.status, e.created_by, e.created_at, e.updated_at FROM event e WHERE e.organization_id = :org AND e.id = :id").param("org", org).param("id", id).query((rs, row) -> map(rs)).optional(); }
    Event insert(UUID org, EventWrite write, UUID actor, String docs, Instant now) { UUID id = UUID.randomUUID(); jdbc.sql("INSERT INTO event (id, organization_id, title, type, section_id, description, starts_at, ends_at, location, cost_per_athlete, target_amount, collection_due_on, response_deadline, required_document_types, status, created_by, created_at, updated_at) VALUES (:id, :org, :title, :type, :sectionId, :description, :startsAt, :endsAt, :location, :cost, :target, :due, :deadline, CAST(:docs AS jsonb), 'DRAFT', :actor, :now, :now)").param("id", id).param("org", org).param("title", write.title().trim()).param("type", write.type()).param("sectionId", write.sectionId()).param("description", write.description()).param("startsAt", JdbcTime.toOffsetDateTime(write.startsAt() == null ? null : write.startsAt().toInstant())).param("endsAt", JdbcTime.toOffsetDateTime(write.endsAt() == null ? null : write.endsAt().toInstant())).param("location", write.location()).param("cost", write.costPerAthlete()).param("target", write.targetAmount()).param("due", write.collectionDueOn()).param("deadline", JdbcTime.toOffsetDateTime(write.responseDeadline() == null ? null : write.responseDeadline().toInstant())).param("docs", docs).param("actor", actor).param("now", JdbcTime.toOffsetDateTime(now)).update(); return findById(org, id).orElseThrow(); }
    void patch(UUID org, UUID id, EventPatch patch, String docs, Instant now) { jdbc.sql("UPDATE event SET title = CASE WHEN :titleProvided THEN :title ELSE title END, description = CASE WHEN :descriptionProvided THEN :description ELSE description END, starts_at = CASE WHEN :startsProvided THEN :startsAt ELSE starts_at END, ends_at = CASE WHEN :endsProvided THEN :endsAt ELSE ends_at END, location = CASE WHEN :locationProvided THEN :location ELSE location END, cost_per_athlete = CASE WHEN :costProvided THEN :cost ELSE cost_per_athlete END, target_amount = CASE WHEN :targetProvided THEN :target ELSE target_amount END, collection_due_on = CASE WHEN :dueProvided THEN :due ELSE collection_due_on END, response_deadline = CASE WHEN :deadlineProvided THEN :deadline ELSE response_deadline END, required_document_types = CASE WHEN :docsProvided THEN CAST(:docs AS jsonb) ELSE required_document_types END, status = CASE WHEN :statusProvided THEN :status ELSE status END, updated_at = :now WHERE organization_id = :org AND id = :id").param("titleProvided", patch.has("title")).param("title", patch.title()).param("descriptionProvided", patch.has("description")).param("description", patch.description()).param("startsProvided", patch.has("startsAt")).param("startsAt", JdbcTime.toOffsetDateTime(patch.startsAt() == null ? null : patch.startsAt().toInstant())).param("endsProvided", patch.has("endsAt")).param("endsAt", JdbcTime.toOffsetDateTime(patch.endsAt() == null ? null : patch.endsAt().toInstant())).param("locationProvided", patch.has("location")).param("location", patch.location()).param("costProvided", patch.has("costPerAthlete")).param("cost", patch.costPerAthlete()).param("targetProvided", patch.has("targetAmount")).param("target", patch.targetAmount()).param("dueProvided", patch.has("collectionDueOn")).param("due", patch.collectionDueOn()).param("deadlineProvided", patch.has("responseDeadline")).param("deadline", JdbcTime.toOffsetDateTime(patch.responseDeadline() == null ? null : patch.responseDeadline().toInstant())).param("docsProvided", patch.has("requiredDocumentTypes")).param("docs", docs).param("statusProvided", patch.has("status")).param("status", patch.status()).param("now", JdbcTime.toOffsetDateTime(now)).param("org", org).param("id", id).update(); }
    void addParticipants(UUID eventId, List<UUID> athleteIds) { for (UUID athleteId : athleteIds) jdbc.sql("INSERT INTO event_participant (event_id, athlete_id) VALUES (:eventId, :athleteId) ON CONFLICT (event_id, athlete_id) DO NOTHING").param("eventId", eventId).param("athleteId", athleteId).update(); }
    void removeParticipant(UUID eventId, UUID athleteId) { jdbc.sql("DELETE FROM event_participant WHERE event_id = :eventId AND athlete_id = :athleteId").param("eventId", eventId).param("athleteId", athleteId).update(); }
    boolean participant(UUID eventId, UUID athleteId) { return jdbc.sql("SELECT count(*) FROM event_participant WHERE event_id = :eventId AND athlete_id = :athleteId").param("eventId", eventId).param("athleteId", athleteId).query(Long.class).single() > 0; }
    List<EventParticipant> participants(UUID eventId) { return jdbc.sql("SELECT ep.athlete_id, concat_ws(' ', a.first_name, a.last_name, a.middle_name) athlete_name, ep.response, ep.responded_by, ep.responded_at, ep.comment, ep.document_ids::text document_ids FROM event_participant ep JOIN athlete a ON a.id = ep.athlete_id WHERE ep.event_id = :eventId ORDER BY athlete_name, ep.athlete_id").param("eventId", eventId).query((rs, row) -> new EventParticipant(rs.getObject("athlete_id", UUID.class), rs.getString("athlete_name"), rs.getString("response"), rs.getObject("responded_by", UUID.class), rs.getTimestamp("responded_at") == null ? null : rs.getTimestamp("responded_at").toInstant(), rs.getString("comment"), readIds(rs.getString("document_ids")))).list(); }
    void respond(UUID eventId, UUID athleteId, UUID actor, String response, String comment, Instant now) { jdbc.sql("UPDATE event_participant SET response = :response, responded_by = :actor, responded_at = :now, comment = :comment WHERE event_id = :eventId AND athlete_id = :athleteId").param("response", response).param("actor", actor).param("now", JdbcTime.toOffsetDateTime(now)).param("comment", comment).param("eventId", eventId).param("athleteId", athleteId).update(); }
    private String eventSql(String select) { return select + " WHERE e.organization_id = :org AND (:q IS NULL OR position(:q IN lower(e.title)) > 0) AND (:fromDate IS NULL OR COALESCE(e.collection_due_on, (e.starts_at AT TIME ZONE 'UTC')::date) >= :fromDate) AND (:toDate IS NULL OR COALESCE(e.collection_due_on, (e.starts_at AT TIME ZONE 'UTC')::date) <= :toDate) AND (:type IS NULL OR e.type = :type) AND (:status IS NULL OR e.status = :status) AND (:scopeUser IS NULL OR EXISTS (SELECT 1 FROM event_participant ep WHERE ep.event_id = e.id AND ep.athlete_id IN (SELECT a.id FROM athlete a WHERE a.user_id = :scopeUser OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :scopeUser))))"; }
    private Event map(java.sql.ResultSet rs) throws java.sql.SQLException { return new Event(rs.getObject("id", UUID.class), rs.getObject("organization_id", UUID.class), rs.getString("title"), rs.getString("type"), rs.getObject("section_id", UUID.class), rs.getString("description"), rs.getTimestamp("starts_at") == null ? null : rs.getTimestamp("starts_at").toInstant(), rs.getTimestamp("ends_at") == null ? null : rs.getTimestamp("ends_at").toInstant(), rs.getString("location"), rs.getBigDecimal("cost_per_athlete"), rs.getBigDecimal("target_amount"), rs.getObject("collection_due_on", LocalDate.class), rs.getTimestamp("response_deadline") == null ? null : rs.getTimestamp("response_deadline").toInstant(), readStrings(rs.getString("required_document_types")), rs.getString("status"), rs.getObject("created_by", UUID.class), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()); }
    private List<String> readStrings(String value) { try { return mapper.readValue(value, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored event data is invalid", e); } }
    private List<UUID> readIds(String value) { try { return mapper.readValue(value, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored event data is invalid", e); } }
    record MembershipAccess(List<String> roles, List<String> permissions) { boolean role(String value) { return roles.contains(value); } boolean permission(String value) { return permissions.contains(value); } }
}