package ru.sportorg.trainings;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class TrainingRepository {
    private final JdbcClient jdbc;
    private final ObjectMapper mapper;
    TrainingRepository(JdbcClient jdbc, ObjectMapper mapper) { this.jdbc = jdbc; this.mapper = mapper; }

    boolean organizationExists(UUID id) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :id").param("id", id).query(Long.class).single() > 0; }
    Optional<MembershipAccess> membership(UUID userId, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :userId AND organization_id = :org AND status = 'ACTIVE'").param("userId", userId).param("org", org).query((rs, row) -> new MembershipAccess(readList(rs.getString("roles")), readList(rs.getString("permissions")))).optional(); }
    boolean groupActive(UUID id, UUID org) { return jdbc.sql("SELECT count(*) FROM sport_group WHERE id = :id AND organization_id = :org AND status = 'ACTIVE'").param("id", id).param("org", org).query(Long.class).single() > 0; }
    boolean activeCoach(UUID id, UUID org) { return jdbc.sql("SELECT count(*) FROM membership WHERE user_id = :id AND organization_id = :org AND status = 'ACTIVE' AND roles @> jsonb_build_array('TRAINER')").param("id", id).param("org", org).query(Long.class).single() > 0; }

    long count(UUID org, String q, Instant from, Instant to, UUID groupId, UUID coachId, String status) { return jdbc.sql("SELECT count(*) FROM training t WHERE t.organization_id = :org AND t.starts_at < :to AND t.ends_at > :from AND (:q IS NULL OR position(:q IN lower(t.title)) > 0) AND (:groupId IS NULL OR t.group_id = :groupId) AND (:coachId IS NULL OR EXISTS (SELECT 1 FROM training_coach tc WHERE tc.training_id = t.id AND tc.coach_id = :coachId)) AND (:status IS NULL OR t.status = :status)").param("org", org).param("q", q).param("from", from).param("to", to).param("groupId", groupId).param("coachId", coachId).param("status", status).query(Long.class).single(); }
    List<Training> find(UUID org, String q, Instant from, Instant to, UUID groupId, UUID coachId, String status, int limit, int offset) { return jdbc.sql("SELECT t.id, t.organization_id, t.title, t.group_id, t.venue_id, t.type_id, t.starts_at, t.ends_at, t.plan::text plan, t.comment, t.status, t.cancel_reason, t.created_at, t.updated_at FROM training t WHERE t.organization_id = :org AND t.starts_at < :to AND t.ends_at > :from AND (:q IS NULL OR position(:q IN lower(t.title)) > 0) AND (:groupId IS NULL OR t.group_id = :groupId) AND (:coachId IS NULL OR EXISTS (SELECT 1 FROM training_coach tc WHERE tc.training_id = t.id AND tc.coach_id = :coachId)) AND (:status IS NULL OR t.status = :status) ORDER BY t.starts_at, t.id LIMIT :limit OFFSET :offset").param("org", org).param("q", q).param("from", from).param("to", to).param("groupId", groupId).param("coachId", coachId).param("status", status).param("limit", limit).param("offset", offset).query((rs, row) -> map(rs)).list(); }
    Optional<Training> findById(UUID org, UUID id) { return jdbc.sql("SELECT t.id, t.organization_id, t.title, t.group_id, t.venue_id, t.type_id, t.starts_at, t.ends_at, t.plan::text plan, t.comment, t.status, t.cancel_reason, t.created_at, t.updated_at FROM training t WHERE t.organization_id = :org AND t.id = :id").param("org", org).param("id", id).query((rs, row) -> map(rs)).optional(); }
    Training insert(UUID org, TrainingWrite write, String plan, Instant now) { UUID id = UUID.randomUUID(); jdbc.sql("INSERT INTO training (id, organization_id, title, group_id, venue_id, type_id, starts_at, ends_at, plan, comment, status, created_at, updated_at) VALUES (:id, :org, :title, :groupId, :venueId, :typeId, :startsAt, :endsAt, CAST(:plan AS jsonb), :comment, 'PLANNED', :now, :now)").param("id", id).param("org", org).param("title", write.title().trim()).param("groupId", write.groupId()).param("venueId", write.venueId()).param("typeId", write.typeId()).param("startsAt", write.startsAt().toInstant()).param("endsAt", write.endsAt().toInstant()).param("plan", plan).param("comment", write.comment()).param("now", now).update(); replaceCoaches(id, write.coachIds()); return findById(org, id).orElseThrow(); }
    void patch(UUID org, UUID id, TrainingPatch patch, String plan, Instant now) { jdbc.sql("UPDATE training SET title = CASE WHEN :titleProvided THEN :title ELSE title END, group_id = CASE WHEN :groupProvided THEN :groupId ELSE group_id END, venue_id = CASE WHEN :venueProvided THEN :venueId ELSE venue_id END, type_id = CASE WHEN :typeProvided THEN :typeId ELSE type_id END, starts_at = CASE WHEN :startsProvided THEN :startsAt ELSE starts_at END, ends_at = CASE WHEN :endsProvided THEN :endsAt ELSE ends_at END, plan = CASE WHEN :planProvided THEN CAST(:plan AS jsonb) ELSE plan END, comment = CASE WHEN :commentProvided THEN :comment ELSE comment END, status = CASE WHEN :statusProvided THEN :status ELSE status END, cancel_reason = CASE WHEN :cancelReasonProvided THEN :cancelReason ELSE cancel_reason END, updated_at = :now WHERE organization_id = :org AND id = :id").param("titleProvided", patch.has("title")).param("title", patch.title()).param("groupProvided", patch.has("groupId")).param("groupId", patch.groupId()).param("venueProvided", patch.has("venueId")).param("venueId", patch.venueId()).param("typeProvided", patch.has("typeId")).param("typeId", patch.typeId()).param("startsProvided", patch.has("startsAt")).param("startsAt", patch.startsAt() == null ? null : patch.startsAt().toInstant()).param("endsProvided", patch.has("endsAt")).param("endsAt", patch.endsAt() == null ? null : patch.endsAt().toInstant()).param("planProvided", patch.has("plan")).param("plan", plan).param("commentProvided", patch.has("comment")).param("comment", patch.comment()).param("statusProvided", patch.has("status")).param("status", patch.status()).param("cancelReasonProvided", patch.has("cancelReason")).param("cancelReason", patch.cancelReason()).param("now", now).param("org", org).param("id", id).update(); if (patch.has("coachIds")) replaceCoaches(id, patch.coachIds()); }
    void replaceCoaches(UUID trainingId, List<UUID> coaches) { jdbc.sql("DELETE FROM training_coach WHERE training_id = :id").param("id", trainingId).update(); for (UUID coach : coaches) jdbc.sql("INSERT INTO training_coach (training_id, coach_id) VALUES (:id, :coach)").param("id", trainingId).param("coach", coach).update(); }
    Optional<TrainingReport> report(UUID trainingId) { return jdbc.sql("SELECT training_id, topic, actual_content, comment, status, author_id, updated_at, closed_at FROM training_report WHERE training_id = :id").param("id", trainingId).query((rs, row) -> new TrainingReport(rs.getObject("training_id", UUID.class), rs.getString("topic"), rs.getString("actual_content"), rs.getString("comment"), rs.getString("status"), rs.getObject("author_id", UUID.class), rs.getTimestamp("updated_at").toInstant(), rs.getTimestamp("closed_at") == null ? null : rs.getTimestamp("closed_at").toInstant())).optional(); }
    void saveReport(UUID trainingId, TrainingReportWrite write, UUID authorId, Instant now, boolean close) { jdbc.sql("INSERT INTO training_report (training_id, topic, actual_content, comment, status, author_id, updated_at, closed_at) VALUES (:id, :topic, :content, :comment, :status, :author, :now, CASE WHEN :close THEN :now ELSE NULL END) ON CONFLICT (training_id) DO UPDATE SET topic = EXCLUDED.topic, actual_content = EXCLUDED.actual_content, comment = EXCLUDED.comment, status = EXCLUDED.status, author_id = EXCLUDED.author_id, updated_at = EXCLUDED.updated_at, closed_at = CASE WHEN :close THEN EXCLUDED.closed_at ELSE training_report.closed_at END").param("id", trainingId).param("topic", write.topic().trim()).param("content", write.actualContent().trim()).param("comment", write.comment()).param("status", write.status()).param("author", authorId).param("now", now).param("close", close).update(); if (close) jdbc.sql("UPDATE training SET status = 'COMPLETED', updated_at = :now WHERE id = :id").param("id", trainingId).param("now", now).update(); }
    List<UUID> participantIds(UUID trainingId) { return jdbc.sql("SELECT ga.athlete_id FROM group_athlete ga JOIN training t ON t.group_id = ga.group_id WHERE t.id = :trainingId AND ga.joined_on <= (t.starts_at AT TIME ZONE 'UTC')::date AND (ga.left_on IS NULL OR ga.left_on >= (t.starts_at AT TIME ZONE 'UTC')::date)").param("trainingId", trainingId).query(UUID.class).list(); }
    void snapshotAttendance(UUID trainingId, Instant now) { jdbc.sql("INSERT INTO attendance (training_id, athlete_id, status) SELECT :trainingId, athlete_id, 'UNMARKED' FROM (SELECT ga.athlete_id FROM group_athlete ga JOIN training t ON t.group_id = ga.group_id WHERE t.id = :trainingId AND ga.joined_on <= (t.starts_at AT TIME ZONE 'UTC')::date AND (ga.left_on IS NULL OR ga.left_on >= (t.starts_at AT TIME ZONE 'UTC')::date)) x ON CONFLICT DO NOTHING").param("trainingId", trainingId).param("now", now).update(); }
    void saveAttendance(UUID trainingId, AttendanceWrite item, UUID actorId, Instant now) { jdbc.sql("UPDATE attendance SET status = :status, reason = :reason, comment = :comment, marked_by = :actor, marked_at = :now WHERE training_id = :trainingId AND athlete_id = :athleteId").param("status", item.status()).param("reason", item.reason()).param("comment", item.comment()).param("actor", actorId).param("now", now).param("trainingId", trainingId).param("athleteId", item.athleteId()).update(); }
    List<Attendance> attendance(UUID trainingId) { return jdbc.sql("SELECT a.training_id, a.athlete_id, concat_ws(' ', at.first_name, at.last_name, at.middle_name) athlete_name, a.status, a.reason, a.comment, a.marked_by, a.marked_at FROM attendance a JOIN athlete at ON at.id = a.athlete_id WHERE a.training_id = :id ORDER BY athlete_name, a.athlete_id").param("id", trainingId).query((rs, row) -> new Attendance(rs.getObject("training_id", UUID.class), rs.getObject("athlete_id", UUID.class), rs.getString("athlete_name"), rs.getString("status"), rs.getString("reason"), rs.getString("comment"), rs.getObject("marked_by", UUID.class), rs.getTimestamp("marked_at") == null ? null : rs.getTimestamp("marked_at").toInstant())).list(); }
    private Training map(java.sql.ResultSet rs) throws java.sql.SQLException { UUID id = rs.getObject("id", UUID.class); List<UUID> coaches = jdbc.sql("SELECT coach_id FROM training_coach WHERE training_id = :id ORDER BY coach_id").param("id", id).query(UUID.class).list(); return new Training(id, rs.getObject("organization_id", UUID.class), rs.getString("title"), rs.getObject("group_id", UUID.class), coaches, rs.getObject("venue_id", UUID.class), rs.getObject("type_id", UUID.class), rs.getTimestamp("starts_at").toInstant(), rs.getTimestamp("ends_at").toInstant(), readPlan(rs.getString("plan")), rs.getString("comment"), rs.getString("status"), rs.getString("cancel_reason"), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()); }
    private List<TrainingStage> readPlan(String json) { try { return mapper.readValue(json, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored training plan is invalid", e); } }
    private List<String> readList(String json) { try { return mapper.readValue(json, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored membership data is invalid", e); } }
    record MembershipAccess(List<String> roles, List<String> permissions) { boolean role(String value) { return roles.contains(value); } boolean permission(String value) { return permissions.contains(value); } }
}