package ru.sportorg.announcements;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import ru.sportorg.jdbc.JdbcTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class AnnouncementRepository {
    private final JdbcClient jdbc; private final ObjectMapper mapper;
    AnnouncementRepository(JdbcClient jdbc, ObjectMapper mapper) { this.jdbc = jdbc; this.mapper = mapper; }
    boolean organizationExists(UUID org) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :org").param("org", org).query(Long.class).single() > 0; }
    Optional<MembershipAccess> membership(UUID userId, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :userId AND organization_id = :org AND status = 'ACTIVE'").param("userId", userId).param("org", org).query((rs, row) -> new MembershipAccess(read(rs.getString("roles")), read(rs.getString("permissions")))).optional(); }
    boolean member(UUID org, UUID userId) { return jdbc.sql("SELECT count(*) FROM membership WHERE organization_id = :org AND user_id = :userId AND status = 'ACTIVE'").param("org", org).param("userId", userId).query(Long.class).single() > 0; }
    Announcement insert(UUID org, AnnouncementWrite write, UUID actor, String files, Instant now) { UUID id = UUID.randomUUID(); jdbc.sql("INSERT INTO announcement (id, organization_id, title, text, category, requires_response, response_deadline, attachment_file_ids, status, created_by, created_at, updated_at) VALUES (:id, :org, :title, :text, :category, :requires, :deadline, CAST(:files AS jsonb), 'DRAFT', :actor, :now, :now)").param("id", id).param("org", org).param("title", write.title().trim()).param("text", write.text()).param("category", write.category()).param("requires", write.requiresResponse()).param("deadline", JdbcTime.toOffsetDateTime(write.responseDeadline() == null ? null : write.responseDeadline().toInstant())).param("files", files).param("actor", actor).param("now", JdbcTime.toOffsetDateTime(now)).update(); replaceRecipients(id, write.recipientUserIds()); return find(org, id, actor).orElseThrow(); }
    Optional<Announcement> find(UUID org, UUID id, UUID viewer) { return jdbc.sql("SELECT a.id, a.organization_id, a.title, a.text, a.category, a.requires_response, a.response_deadline, a.attachment_file_ids::text files, a.status, a.created_by, a.published_at, a.created_at, a.updated_at, ar.read_at, (SELECT response FROM announcement_response x WHERE x.announcement_id = a.id AND x.user_id = :viewer ORDER BY x.responded_at DESC LIMIT 1) my_response FROM announcement a LEFT JOIN announcement_recipient ar ON ar.announcement_id = a.id AND ar.user_id = :viewer WHERE a.organization_id = :org AND a.id = :id").param("org", org).param("id", id).param("viewer", viewer).query((rs, row) -> map(rs)).optional(); }
    long count(UUID org, String q, UUID viewer, String status, boolean unread, Boolean requiresResponse, boolean drafts, boolean allPublished) { return jdbc.sql("SELECT count(*) FROM announcement a WHERE a.organization_id = :org AND (CAST(:q AS text) IS NULL OR position(:q IN lower(a.title)) > 0) AND (CAST(:status AS text) IS NULL OR a.status = :status) AND (CAST(:requiresResponse AS boolean) IS NULL OR a.requires_response = :requiresResponse) AND (:unread = FALSE OR EXISTS (SELECT 1 FROM announcement_recipient ar WHERE ar.announcement_id = a.id AND ar.user_id = :viewer AND ar.read_at IS NULL)) AND (CASE WHEN a.status = 'DRAFT' THEN :drafts ELSE (:allPublished OR EXISTS (SELECT 1 FROM announcement_recipient ar WHERE ar.announcement_id = a.id AND ar.user_id = :viewer)) END)").param("org", org).param("q", q).param("viewer", viewer).param("status", status).param("unread", unread).param("requiresResponse", requiresResponse).param("drafts", drafts).param("allPublished", allPublished).query(Long.class).single(); }
    List<Announcement> findPage(UUID org, String q, UUID viewer, String status, boolean unread, Boolean requiresResponse, boolean drafts, boolean allPublished, int limit, int offset) { return jdbc.sql("SELECT a.id, a.organization_id, a.title, a.text, a.category, a.requires_response, a.response_deadline, a.attachment_file_ids::text files, a.status, a.created_by, a.published_at, a.created_at, a.updated_at, ar.read_at, (SELECT response FROM announcement_response x WHERE x.announcement_id = a.id AND x.user_id = :viewer ORDER BY x.responded_at DESC LIMIT 1) my_response FROM announcement a LEFT JOIN announcement_recipient ar ON ar.announcement_id = a.id AND ar.user_id = :viewer WHERE a.organization_id = :org AND (CAST(:q AS text) IS NULL OR position(:q IN lower(a.title)) > 0) AND (CAST(:status AS text) IS NULL OR a.status = :status) AND (CAST(:requiresResponse AS boolean) IS NULL OR a.requires_response = :requiresResponse) AND (:unread = FALSE OR ar.read_at IS NULL) AND (CASE WHEN a.status = 'DRAFT' THEN :drafts ELSE (:allPublished OR ar.user_id IS NOT NULL) END) ORDER BY a.created_at DESC, a.id DESC LIMIT :limit OFFSET :offset").param("org", org).param("q", q).param("viewer", viewer).param("status", status).param("unread", unread).param("requiresResponse", requiresResponse).param("drafts", drafts).param("allPublished", allPublished).param("limit", limit).param("offset", offset).query((rs, row) -> map(rs)).list(); }
    void replaceRecipients(UUID id, List<UUID> users) { jdbc.sql("DELETE FROM announcement_recipient WHERE announcement_id = :id").param("id", id).update(); for (UUID user : users) jdbc.sql("INSERT INTO announcement_recipient (announcement_id, user_id) VALUES (:id, :user)").param("id", id).param("user", user).update(); }
    void patch(UUID org, UUID id, AnnouncementWrite write, String files, String status, Instant now) { jdbc.sql("UPDATE announcement SET title = :title, text = :text, category = :category, requires_response = :requires, response_deadline = :deadline, attachment_file_ids = CAST(:files AS jsonb), status = :status, published_at = CASE WHEN :status = 'PUBLISHED' AND published_at IS NULL THEN :now ELSE published_at END, updated_at = :now WHERE organization_id = :org AND id = :id").param("title", write.title().trim()).param("text", write.text()).param("category", write.category()).param("requires", write.requiresResponse()).param("deadline", JdbcTime.toOffsetDateTime(write.responseDeadline() == null ? null : write.responseDeadline().toInstant())).param("files", files).param("status", status).param("now", JdbcTime.toOffsetDateTime(now)).param("org", org).param("id", id).update(); replaceRecipients(id, write.recipientUserIds()); }
    // Архивирование опубликованного: текст, вложения и получатели остаются как были (6.12, №050)
    void archive(UUID org, UUID id, Instant now) { jdbc.sql("UPDATE announcement SET status = 'ARCHIVED', updated_at = :now WHERE organization_id = :org AND id = :id").param("now", JdbcTime.toOffsetDateTime(now)).param("org", org).param("id", id).update(); }
    void markRead(UUID id, UUID user, Instant now) { jdbc.sql("UPDATE announcement_recipient SET read_at = COALESCE(read_at, :now) WHERE announcement_id = :id AND user_id = :user").param("id", id).param("user", user).param("now", JdbcTime.toOffsetDateTime(now)).update(); }
    boolean recipient(UUID id, UUID user) { return jdbc.sql("SELECT count(*) FROM announcement_recipient WHERE announcement_id = :id AND user_id = :user").param("id", id).param("user", user).query(Long.class).single() > 0; }
    void response(UUID id, UUID user, String response, String comment, Instant now) { jdbc.sql("INSERT INTO announcement_response (announcement_id, user_id, response, comment, responded_at) VALUES (:id, :user, :response, :comment, :now)").param("id", id).param("user", user).param("response", response).param("comment", comment).param("now", JdbcTime.toOffsetDateTime(now)).update(); }
    private Announcement map(java.sql.ResultSet rs) throws java.sql.SQLException { return new Announcement(rs.getObject("id", UUID.class), rs.getObject("organization_id", UUID.class), rs.getString("title"), rs.getString("text"), rs.getString("category"), rs.getBoolean("requires_response"), rs.getTimestamp("response_deadline") == null ? null : rs.getTimestamp("response_deadline").toInstant(), readIds(rs.getString("files")), rs.getString("status"), rs.getObject("created_by", UUID.class), rs.getTimestamp("published_at") == null ? null : rs.getTimestamp("published_at").toInstant(), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant(), rs.getTimestamp("read_at") == null ? null : rs.getTimestamp("read_at").toInstant(), rs.getString("my_response")); }
    private List<String> read(String value) { try { return mapper.readValue(value, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored announcement data is invalid", e); } }
    private List<UUID> readIds(String value) { try { return mapper.readValue(value, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored announcement data is invalid", e); } }
    boolean exists(UUID org, UUID id) { return jdbc.sql("SELECT count(*) FROM announcement WHERE organization_id = :org AND id = :id").param("org", org).param("id", id).query(Long.class).single() > 0; }
    long countRecipients(UUID id) { return jdbc.sql("SELECT count(*) FROM announcement_recipient WHERE announcement_id = :id").param("id", id).query(Long.class).single(); }
    List<AnnouncementRecipient> recipients(UUID id, int limit, int offset) {
        return jdbc.sql("SELECT r.user_id, u.full_name, r.read_at, lr.response, lr.responded_at FROM announcement_recipient r JOIN app_user u ON u.id = r.user_id"
                        + " LEFT JOIN LATERAL (SELECT ar.response, ar.responded_at FROM announcement_response ar WHERE ar.announcement_id = r.announcement_id AND ar.user_id = r.user_id ORDER BY ar.responded_at DESC LIMIT 1) lr ON true"
                        + " WHERE r.announcement_id = :id ORDER BY u.full_name, r.user_id LIMIT :limit OFFSET :offset")
                .param("id", id).param("limit", limit).param("offset", offset)
                .query((rs, row) -> new AnnouncementRecipient(rs.getObject("user_id", UUID.class), rs.getString("full_name"),
                        rs.getTimestamp("read_at") == null ? null : rs.getTimestamp("read_at").toInstant(), rs.getString("response"),
                        rs.getTimestamp("responded_at") == null ? null : rs.getTimestamp("responded_at").toInstant()))
                .list();
    }
    long countResponses(UUID id, UUID userId) { return jdbc.sql("SELECT count(*) FROM announcement_response WHERE announcement_id = :id AND (CAST(:userId AS uuid) IS NULL OR user_id = :userId)").param("id", id).param("userId", userId).query(Long.class).single(); }
    List<AnnouncementResponseEntry> responses(UUID id, UUID userId, int limit, int offset) {
        return jdbc.sql("SELECT ar.id, ar.announcement_id, ar.user_id, u.full_name, ar.response, ar.comment, ar.responded_at FROM announcement_response ar JOIN app_user u ON u.id = ar.user_id"
                        + " WHERE ar.announcement_id = :id AND (CAST(:userId AS uuid) IS NULL OR ar.user_id = :userId) ORDER BY ar.responded_at DESC, ar.id DESC LIMIT :limit OFFSET :offset")
                .param("id", id).param("userId", userId).param("limit", limit).param("offset", offset)
                .query((rs, row) -> new AnnouncementResponseEntry(rs.getObject("id", UUID.class), rs.getObject("announcement_id", UUID.class),
                        rs.getObject("user_id", UUID.class), rs.getString("full_name"), rs.getString("response"), rs.getString("comment"),
                        rs.getTimestamp("responded_at").toInstant()))
                .list();
    }
    record MembershipAccess(List<String> roles, List<String> permissions) { boolean role(String value) { return roles.contains(value); } boolean permission(String value) { return permissions.contains(value); } }
}