package ru.sportorg.dashboard;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class DashboardRepository {
    private final JdbcClient jdbc;
    DashboardRepository(JdbcClient jdbc) { this.jdbc = jdbc; }
    boolean organizationExists(UUID org) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :org").param("org", org).query(Long.class).single() > 0; }
    Membership membership(UUID user, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :user AND organization_id = :org AND status = 'ACTIVE'").param("user", user).param("org", org).query((rs, row) -> new Membership(rs.getString("roles"), rs.getString("permissions"))).optional().orElse(null); }
    boolean athleteVisible(UUID org, UUID athlete, UUID user) { return jdbc.sql("SELECT count(*) FROM athlete a WHERE a.organization_id = :org AND a.id = :athlete AND (a.user_id = :user OR EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :user))").param("org", org).param("athlete", athlete).param("user", user).query(Long.class).single() > 0; }
    int athletes(UUID org, UUID athlete) { return athlete == null ? jdbc.sql("SELECT count(*) FROM athlete WHERE organization_id = :org AND status = 'ACTIVE'").param("org", org).query(Integer.class).single() : jdbc.sql("SELECT count(*) FROM athlete WHERE organization_id = :org AND id = :athlete AND status = 'ACTIVE'").param("org", org).param("athlete", athlete).query(Integer.class).single(); }
    int groups(UUID org, UUID athlete) { return athlete == null ? jdbc.sql("SELECT count(*) FROM sport_group WHERE organization_id = :org AND status = 'ACTIVE'").param("org", org).query(Integer.class).single() : jdbc.sql("SELECT count(DISTINCT group_id) FROM group_athlete WHERE athlete_id = :athlete AND left_on IS NULL").param("athlete", athlete).query(Integer.class).single(); }
    int upcomingTrainings(UUID org, Instant from, Instant to, UUID athlete) { return jdbc.sql("SELECT count(*) FROM training t WHERE t.organization_id = :org AND t.starts_at >= :fromTime AND t.starts_at < :toTime AND t.starts_at > CURRENT_TIMESTAMP AND t.status = 'PLANNED' AND (:athlete IS NULL OR EXISTS (SELECT 1 FROM group_athlete ga WHERE ga.group_id = t.group_id AND ga.athlete_id = :athlete AND ga.left_on IS NULL))").param("org", org).param("fromTime", from).param("toTime", to).param("athlete", athlete).query(Integer.class).single(); }
    int upcomingEvents(UUID org, LocalDate from, LocalDate to, UUID athlete) { return jdbc.sql("SELECT count(*) FROM event e WHERE e.organization_id = :org AND e.status = 'PUBLISHED' AND COALESCE(e.collection_due_on, (e.starts_at AT TIME ZONE 'UTC')::date) BETWEEN :fromDate AND :toDate AND (:athlete IS NULL OR EXISTS (SELECT 1 FROM event_participant ep WHERE ep.event_id = e.id AND ep.athlete_id = :athlete))").param("org", org).param("fromDate", from).param("toDate", to).param("athlete", athlete).query(Integer.class).single(); }
    List<DashboardTraining> nextTrainings(UUID org, Instant from, Instant to, UUID athlete) { return jdbc.sql("SELECT t.id, t.title, t.group_id, t.starts_at, t.ends_at, t.status FROM training t WHERE t.organization_id = :org AND t.starts_at >= :fromTime AND t.starts_at < :toTime AND t.starts_at > CURRENT_TIMESTAMP AND t.status = 'PLANNED' AND (:athlete IS NULL OR EXISTS (SELECT 1 FROM group_athlete ga WHERE ga.group_id = t.group_id AND ga.athlete_id = :athlete AND ga.left_on IS NULL)) ORDER BY t.starts_at, t.id LIMIT 5").param("org", org).param("fromTime", from).param("toTime", to).param("athlete", athlete).query((rs, row) -> new DashboardTraining(rs.getObject("id", UUID.class), rs.getString("title"), rs.getObject("group_id", UUID.class), rs.getTimestamp("starts_at").toInstant(), rs.getTimestamp("ends_at").toInstant(), rs.getString("status"))).list(); }
    List<DashboardEvent> nextEvents(UUID org, LocalDate from, LocalDate to, UUID athlete) { return jdbc.sql("SELECT e.id, e.title, e.type, e.starts_at, e.collection_due_on, e.status FROM event e WHERE e.organization_id = :org AND e.status = 'PUBLISHED' AND COALESCE(e.collection_due_on, (e.starts_at AT TIME ZONE 'UTC')::date) BETWEEN :fromDate AND :toDate AND (:athlete IS NULL OR EXISTS (SELECT 1 FROM event_participant ep WHERE ep.event_id = e.id AND ep.athlete_id = :athlete)) ORDER BY COALESCE(e.collection_due_on, (e.starts_at AT TIME ZONE 'UTC')::date), e.id LIMIT 5").param("org", org).param("fromDate", from).param("toDate", to).param("athlete", athlete).query((rs, row) -> new DashboardEvent(rs.getObject("id", UUID.class), rs.getString("title"), rs.getString("type"), rs.getTimestamp("starts_at") == null ? null : rs.getTimestamp("starts_at").toInstant(), rs.getObject("collection_due_on", LocalDate.class), rs.getString("status"))).list(); }
    Finance finance(UUID org, UUID athlete) { return jdbc.sql("SELECT COALESCE(SUM(c.amount - COALESCE((SELECT SUM(p.amount) FROM payment p WHERE p.charge_id = c.id AND p.status = 'ACTIVE'), 0)), 0) outstanding, COALESCE(SUM(CASE WHEN c.due_on < CURRENT_DATE THEN c.amount - COALESCE((SELECT SUM(p2.amount) FROM payment p2 WHERE p2.charge_id = c.id AND p2.status = 'ACTIVE'), 0) ELSE 0 END), 0) overdue FROM charge c WHERE c.organization_id = :org AND c.status = 'ACTIVE' AND (:athlete IS NULL OR c.athlete_id = :athlete)").param("org", org).param("athlete", athlete).query((rs, row) -> new Finance(rs.getBigDecimal("outstanding"), rs.getBigDecimal("overdue"))).single(); }
    long activityCount(UUID org) { return jdbc.sql("SELECT count(*) FROM activity WHERE organization_id = :org").param("org", org).query(Long.class).single(); }
    List<Activity> activities(UUID org, int limit, int offset) { return jdbc.sql("SELECT a.id, a.actor_id, u.full_name actor_name, a.action, a.entity_type, a.entity_id, a.title, a.created_at FROM activity a JOIN app_user u ON u.id = a.actor_id WHERE a.organization_id = :org ORDER BY a.created_at DESC, a.id DESC LIMIT :limit OFFSET :offset").param("org", org).param("limit", limit).param("offset", offset).query((rs, row) -> new Activity(rs.getObject("id", UUID.class), rs.getObject("actor_id", UUID.class), rs.getString("actor_name"), rs.getString("action"), rs.getString("entity_type"), rs.getObject("entity_id", UUID.class), rs.getString("title"), rs.getTimestamp("created_at").toInstant())).list(); }
    record Membership(String roles, String permissions) { boolean role(String v) { return roles.contains(v); } boolean permission(String v) { return permissions.contains(v); } }
    record Finance(BigDecimal outstanding, BigDecimal overdue) { }
}