package ru.sportorg.progress;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import ru.sportorg.jdbc.JdbcTime;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.stereotype.Repository;

@Repository
class ProgressRepository {
    private final JdbcClient jdbc;
    private final ObjectMapper mapper;
    ProgressRepository(JdbcClient jdbc, ObjectMapper mapper) { this.jdbc = jdbc; this.mapper = mapper; }
    boolean organizationExists(UUID org) { return jdbc.sql("SELECT count(*) FROM organization WHERE id = :org").param("org", org).query(Long.class).single() > 0; }
    Optional<MembershipAccess> membership(UUID userId, UUID org) { return jdbc.sql("SELECT roles::text roles, permissions::text permissions FROM membership WHERE user_id = :userId AND organization_id = :org AND status = 'ACTIVE'").param("userId", userId).param("org", org).query((rs, row) -> new MembershipAccess(read(rs.getString("roles")), read(rs.getString("permissions")))).optional(); }
    boolean athleteExists(UUID org, UUID athleteId) { return jdbc.sql("SELECT count(*) FROM athlete WHERE organization_id = :org AND id = :id").param("org", org).param("id", athleteId).query(Long.class).single() > 0; }
    boolean athleteVisible(UUID org, UUID athleteId, UUID userId, String scope) { return jdbc.sql("SELECT count(*) FROM athlete a WHERE a.organization_id = :org AND a.id = :athleteId AND ((:scope IN ('PARENT','BOTH') AND EXISTS (SELECT 1 FROM parent_link pl WHERE pl.athlete_id = a.id AND pl.parent_user_id = :userId)) OR (:scope IN ('ATHLETE','BOTH') AND a.user_id = :userId) OR CAST(:scope AS text) IS NULL)").param("org", org).param("athleteId", athleteId).param("userId", userId).param("scope", scope).query(Long.class).single() > 0; }

    long resultCount(UUID org, UUID athleteId, LocalDate from, LocalDate to, String metricName, String unit) { return jdbc.sql("SELECT count(*) FROM athlete_result WHERE organization_id = :org AND athlete_id = :athleteId AND (CAST(:fromDate AS date) IS NULL OR measured_on >= :fromDate) AND (CAST(:toDate AS date) IS NULL OR measured_on <= :toDate) AND (CAST(:metricName AS text) IS NULL OR lower(metric_name) = :metricName) AND (CAST(:unit AS text) IS NULL OR unit = :unit)").param("org", org).param("athleteId", athleteId).param("fromDate", from).param("toDate", to).param("metricName", metricName).param("unit", unit).query(Long.class).single(); }
    List<Result> results(UUID org, UUID athleteId, LocalDate from, LocalDate to, String metricName, String unit, int limit, int offset) { return jdbc.sql("SELECT id, athlete_id, metric_name, value, unit, measured_on, comment, is_personal_best, created_by, created_at, updated_at FROM athlete_result WHERE organization_id = :org AND athlete_id = :athleteId AND (CAST(:fromDate AS date) IS NULL OR measured_on >= :fromDate) AND (CAST(:toDate AS date) IS NULL OR measured_on <= :toDate) AND (CAST(:metricName AS text) IS NULL OR lower(metric_name) = :metricName) AND (CAST(:unit AS text) IS NULL OR unit = :unit) ORDER BY measured_on, id LIMIT :limit OFFSET :offset").param("org", org).param("athleteId", athleteId).param("fromDate", from).param("toDate", to).param("metricName", metricName).param("unit", unit).param("limit", limit).param("offset", offset).query((rs, row) -> result(rs)).list(); }
    Result insertResult(UUID org, UUID athleteId, ResultWrite write, UUID actor, Instant now) { UUID id = UUID.randomUUID(); jdbc.sql("INSERT INTO athlete_result (id, organization_id, athlete_id, metric_name, value, unit, measured_on, comment, is_personal_best, created_by, created_at, updated_at) VALUES (:id, :org, :athleteId, :metricName, :value, :unit, :measuredOn, :comment, :best, :actor, :now, :now)").param("id", id).param("org", org).param("athleteId", athleteId).param("metricName", write.metricName().trim()).param("value", write.value()).param("unit", write.unit().trim()).param("measuredOn", write.measuredOn()).param("comment", write.comment()).param("best", write.isPersonalBest()).param("actor", actor).param("now", JdbcTime.toOffsetDateTime(now)).update(); return resultById(org, athleteId, id).orElseThrow(); }
    Optional<Result> resultById(UUID org, UUID athleteId, UUID id) { return jdbc.sql("SELECT id, athlete_id, metric_name, value, unit, measured_on, comment, is_personal_best, created_by, created_at, updated_at FROM athlete_result WHERE organization_id = :org AND athlete_id = :athleteId AND id = :id").param("org", org).param("athleteId", athleteId).param("id", id).query((rs, row) -> result(rs)).optional(); }
    void patchResult(UUID org, UUID athleteId, UUID id, ResultPatch patch, Instant now) { jdbc.sql("UPDATE athlete_result SET metric_name = CASE WHEN :metricProvided THEN :metricName ELSE metric_name END, value = CASE WHEN :valueProvided THEN :value ELSE value END, unit = CASE WHEN :unitProvided THEN :unit ELSE unit END, measured_on = CASE WHEN :dateProvided THEN :measuredOn ELSE measured_on END, comment = CASE WHEN :commentProvided THEN :comment ELSE comment END, is_personal_best = CASE WHEN :bestProvided THEN :best ELSE is_personal_best END, updated_at = :now WHERE organization_id = :org AND athlete_id = :athleteId AND id = :id").param("metricProvided", patch.has("metricName")).param("metricName", patch.metricName()).param("valueProvided", patch.has("value")).param("value", patch.value()).param("unitProvided", patch.has("unit")).param("unit", patch.unit()).param("dateProvided", patch.has("measuredOn")).param("measuredOn", patch.measuredOn()).param("commentProvided", patch.has("comment")).param("comment", patch.comment()).param("bestProvided", patch.has("isPersonalBest")).param("best", patch.personalBest()).param("now", JdbcTime.toOffsetDateTime(now)).param("org", org).param("athleteId", athleteId).param("id", id).update(); }
    void deleteResult(UUID org, UUID athleteId, UUID id) { jdbc.sql("DELETE FROM athlete_result WHERE organization_id = :org AND athlete_id = :athleteId AND id = :id").param("org", org).param("athleteId", athleteId).param("id", id).update(); }
    List<AthleteStandard> standards(UUID org, UUID athleteId, int limit, int offset) { return jdbc.sql("SELECT id, athlete_id, name, target_text, result_text, assessed_on, status, comment FROM athlete_standard WHERE organization_id = :org AND athlete_id = :athleteId ORDER BY assessed_on, id LIMIT :limit OFFSET :offset").param("org", org).param("athleteId", athleteId).param("limit", limit).param("offset", offset).query((rs, row) -> new AthleteStandard(rs.getObject("id", UUID.class), rs.getObject("athlete_id", UUID.class), rs.getString("name"), rs.getString("target_text"), rs.getString("result_text"), rs.getObject("assessed_on", LocalDate.class), rs.getString("status"), rs.getString("comment"))).list(); }
    long standardCount(UUID org, UUID athleteId) { return jdbc.sql("SELECT count(*) FROM athlete_standard WHERE organization_id = :org AND athlete_id = :athleteId").param("org", org).param("athleteId", athleteId).query(Long.class).single(); }
    List<AthleteRank> ranks(UUID org, UUID athleteId, int limit, int offset) { return jdbc.sql("SELECT id, athlete_id, name, sport_type_id, assigned_on, valid_until, comment FROM athlete_rank WHERE organization_id = :org AND athlete_id = :athleteId ORDER BY assigned_on, id LIMIT :limit OFFSET :offset").param("org", org).param("athleteId", athleteId).param("limit", limit).param("offset", offset).query((rs, row) -> new AthleteRank(rs.getObject("id", UUID.class), rs.getObject("athlete_id", UUID.class), rs.getString("name"), rs.getObject("sport_type_id", UUID.class), rs.getObject("assigned_on", LocalDate.class), rs.getObject("valid_until", LocalDate.class), rs.getString("comment"))).list(); }
    long rankCount(UUID org, UUID athleteId) { return jdbc.sql("SELECT count(*) FROM athlete_rank WHERE organization_id = :org AND athlete_id = :athleteId").param("org", org).param("athleteId", athleteId).query(Long.class).single(); }
    private Result result(java.sql.ResultSet rs) throws java.sql.SQLException { return new Result(rs.getObject("id", UUID.class), rs.getObject("athlete_id", UUID.class), rs.getString("metric_name"), rs.getBigDecimal("value"), rs.getString("unit"), rs.getObject("measured_on", LocalDate.class), rs.getString("comment"), rs.getBoolean("is_personal_best"), rs.getObject("created_by", UUID.class), rs.getTimestamp("created_at").toInstant(), rs.getTimestamp("updated_at").toInstant()); }
    private List<String> read(String json) { try { return mapper.readValue(json, new TypeReference<>() { }); } catch (java.io.IOException e) { throw new IllegalStateException("Stored membership data is invalid", e); } }
    record MembershipAccess(List<String> roles, List<String> permissions) { boolean role(String role) { return roles.contains(role); } boolean permission(String permission) { return permissions.contains(permission); } }
}